=== calzada/ECPC_GITHUB/CORPUS/XXX ECPC Etiquetado Martes 130514/cd.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ep.dtd: EC Parliament sessions. $Revision: 1.6 $ -->
<!-- This dtd is a revision of the ep.dtd 1.6. The main goal is to obtain a dtd to review the EP xml corpus, during comparation and manual fixing before alignment with TCA2 -->
<!ELEMENT ecpc_CD (header,body,back*)>
<!-- Add other new languages, since ECPC will gather debates belonging to sessions held after Romanian, Bulgarian, Gaelic and other new languages were incorporated -->
<!ELEMENT header (legislature,title,label,date,place,edition,index)>
<!ATTLIST header filename CDATA #REQUIRED>
<!ATTLIST header language (CS|DA|DE|EL|EN|ES|ET|FI|FR|HU|IT|LT|LV|MT|NL|PL|PT|SK|SL|SV) #REQUIRED>
<!-- TO BE DONE Add the following item with a regex or script in all files -->
<!ELEMENT legislature (#PCDATA)>
<!ATTLIST legislature begin CDATA #REQUIRED>
<!ATTLIST legislature end CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!-- TO BE DONE (macro?) Date always normalized YYYYMMDD -->
<!ELEMENT date (#PCDATA)>
<!ELEMENT place (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!-- indexitem tags different items within the index. These will be repeated later on throughout the text as header to separate different items in the session -->
<!ELEMENT index (indextitle?|indexitem+|page_number)*>
<!ELEMENT indextitle (#PCDATA)>
<!ELEMENT indexitem (#PCDATA|page_number)*>
<!ATTLIST indexitem number CDATA #IMPLIED>
<!-- Chair tags the person presiding the session over; intervention contains information about speakers plus speeches; headings are the indexitems which now separate parts of the session -->
<!ELEMENT page_number (#PCDATA) >
<!ELEMENT body (chair)+>
<!ELEMENT chair (intervention|heading|omit|page_number)*>
<!ATTLIST chair who CDATA #REQUIRED >
<!-- <!ELEMENT intervention (speaker|speech|writer|writing|omit|italics)*> -->
<!ELEMENT intervention ((speaker|writer)+,(speech|writing)+)>
<!-- TO BE DONE, change attribute ref by attribute id -->
<!ATTLIST intervention id ID #REQUIRED>
<!-- should ID/ref attributes be unique for the whole corpus or it might be enough if they are unique within their text?  System for all the corpus FILENAME-id example -->
<!-- Todos los elementos aparecerán siempre pero cuando no sepamos el nombre pondremos UNKNONW; constituency sería NA; affiliation sería NA normalmente salvo excepciones muy raras; post sería NA porque en ese momento no ejerce ningún cargo-->
<!ELEMENT speaker (name,birth_date,birth_place,status,gender,institution,constituency,affiliation,post)>
<!-- name should eventually apperar without a question mark, once we solve problems with chair -->
<!-- TO BE DONE para president de momento añadir <name>UNKNOWN</name> después rellenar con Chair -->
<!ELEMENT name (#PCDATA)>
<!-- SCRIPT -->
<!ELEMENT birth_date (#PCDATA)>
<!-- birth place means the city/town of birth, it has an attribute for country -->
<!-- SCRIPT -->
<!ELEMENT birth_place (#PCDATA)>
<!-- Birthplace, si no lo sabemos UNKNOWN -->
<!ATTLIST birth_place country (AD|AE|AF|AG|AI|AL|AM|AN|AO|AQ|AR|AS|AT|AU|AW|AX|AZ|BA|BB|BD|BE|BF|BG|BH|BI|BJ|BL|BM|BN|BO|BR|BS|BT|BV|BW|BY|BZ|CA|CC|CD|CF|CG|CH|CI|CK|CL|CM|CN|CO|CP|CR|CU|CV|CX|CY|CZ|DE|DJ|DK|DM|DO|DZ|EC|EE|EG|EH|EL|ER|ES|ET|FI|FJ|FK|FM|FO|FR|MK|GA|GD|GE|GF|GG|GH|GI|GL|GM|GN|GP|GQ|GS|GT|GU|GW|GY|HK|HM|HN|HR|HT|HU|ID|IE|IL|IM|IN|IO|IQ|IR|IS|IT|JE|JM|JO|JP|KE|KG|KH|KI|KM|KN|KP|KR|KW|KY|KZ|LA|LB|LC|LI|LK|LR|LS|LT|LU|LV|LY|MA|MC|MD|ME|MF|MG|MH|ML|MM|MN|MO|MP|MQ|MR|MS|MT|MU|MV|MW|MX|MY|MZ|NA|NC|NE|NF|NG|NI|NL|NO|NP|NR|NU|NZ|OM|PA|PE|PF|PG|PH|PK|PL|PM|PN|PR|PS|PT|PW|PY|QA|RE|RO|RS|RU|RW|SA|SB|SC|SD|SE|SG|SH|SI|SJ|SK|SL|SM|SN|SO|SR|ST|SV|SY|SZ|TC|TD|TF|TG|TH|TJ|TK|TL|TM|TN|TO|TR|TT|TV|TW|TZ|UA|UG|UK|UM|US|UY|UZ|VA|VC|VE|VG|VI|VN|VU|WF|WS|YE|YT|ZA|ZM|ZW|UNKNOWN) #REQUIRED>
<!-- EP institutions might be eu, ni, io, ngo, vip -->
<!-- HC a study should be made, we might use the same as for the EP with a difference, we might mantain eu but without its children, and we need to mantain ni and create new children -as body was for eu- (hc, hl, government, court of appeals, Queen...) even a new category/element should be included ri (regional institution) -->
<!-- CD a study should be made, we might use the same as for the EP with a difference, we might mantain eu but without its children, and we need to mantain ni and create new children -as body was for eu- (cd, senado, gobierno, banco de españa, Rey...) even a new category/element should be included ri (regional institution) -->
<!-- SCRIPT -->
<!ELEMENT status (#PCDATA)>
<!-- SCRIPT -->
<!ELEMENT gender (#PCDATA)>
<!-- SCRIPT -->
<!ELEMENT institution (ni|io|ngo|vip) >
<!-- BODY Might it be improved since we have already an element called body? Not important now, it can be used anyways. The list of bodies might need to be extended as we extend the corpus because more bodies might be represented throughout a whole legislature -->
<!ELEMENT ni (#PCDATA) >
<!-- En el caso del CD sería: <ni country="Spain">CD</ni> o <ni country="Spain">NON-CD</ni> Posteriormente se pueden estudiar las otras instituciones -->
<!-- En el caso del HC sería: <ni country="UK">HC</ni> o <ni country="UK">NON-HC</ni> Posteriormente se pueden estudiar las otras instituciones -->
<!-- En el caso de países de los cuales no estudiamos su parlamento el contenido para este elemento podría ser NON-ECPC -->
<!ATTLIST ni country (AD|AE|AF|AG|AI|AL|AM|AN|AO|AQ|AR|AS|AT|AU|AW|AX|AZ|BA|BB|BD|BE|BF|BG|BH|BI|BJ|BL|BM|BN|BO|BR|BS|BT|BV|BW|BY|BZ|CA|CC|CD|CF|CG|CH|CI|CK|CL|CM|CN|CO|CP|CR|CU|CV|CX|CY|CZ|DE|DJ|DK|DM|DO|DZ|EC|EE|EG|EH|EL|ER|ES|ET|FI|FJ|FK|FM|FO|FR|MK|GA|GD|GE|GF|GG|GH|GI|GL|GM|GN|GP|GQ|GS|GT|GU|GW|GY|HK|HM|HN|HR|HT|HU|ID|IE|IL|IM|IN|IO|IQ|IR|IS|IT|JE|JM|JO|JP|KE|KG|KH|KI|KM|KN|KP|KR|KW|KY|KZ|LA|LB|LC|LI|LK|LR|LS|LT|LU|LV|LY|MA|MC|MD|ME|MF|MG|MH|ML|MM|MN|MO|MP|MQ|MR|MS|MT|MU|MV|MW|MX|MY|MZ|NA|NC|NE|NF|NG|NI|NL|NO|NP|NR|NU|NZ|OM|PA|PE|PF|PG|PH|PK|PL|PM|PN|PR|PS|PT|PW|PY|QA|RE|RO|RS|RU|RW|SA|SB|SC|SD|SE|SG|SH|SI|SJ|SK|SL|SM|SN|SO|SR|ST|SV|SY|SZ|TC|TD|TF|TG|TH|TJ|TK|TL|TM|TN|TO|TR|TT|TV|TW|TZ|UA|UG|UK|UM|US|UY|UZ|VA|VC|VE|VG|VI|VN|VU|WF|WS|YE|YT|ZA|ZM|ZW|UNKNOWN) #REQUIRED >
<!ELEMENT io (eu|non-eu) >
<!ELEMENT eu EMPTY>
<!ATTLIST eu body (EP|Commission|Council|ECB|EIB|Ombudsman|HRFASP|CA) #REQUIRED >
<!ELEMENT non-eu (#PCDATA) >
<!-- NGO is any non governamental group of people with a common goal . El atributo country no es obligatorio, qué pasa sin la ong es internacional, valor international para el atributo country, no ponerlo, desechar el atributo o formalizar de otra manera? -->
<!ELEMENT ngo (#PCDATA) >
<!ATTLIST ngo country (AD|AE|AF|AG|AI|AL|AM|AN|AO|AQ|AR|AS|AT|AU|AW|AX|AZ|BA|BB|BD|BE|BF|BG|BH|BI|BJ|BL|BM|BN|BO|BR|BS|BT|BV|BW|BY|BZ|CA|CC|CD|CF|CG|CH|CI|CK|CL|CM|CN|CO|CP|CR|CU|CV|CX|CY|CZ|DE|DJ|DK|DM|DO|DZ|EC|EE|EG|EH|EL|ER|ES|ET|FI|FJ|FK|FM|FO|FR|MK|GA|GD|GE|GF|GG|GH|GI|GL|GM|GN|GP|GQ|GS|GT|GU|GW|GY|HK|HM|HN|HR|HT|HU|ID|IE|IL|IM|IN|IO|IQ|IR|IS|IT|JE|JM|JO|JP|KE|KG|KH|KI|KM|KN|KP|KR|KW|KY|KZ|LA|LB|LC|LI|LK|LR|LS|LT|LU|LV|LY|MA|MC|MD|ME|MF|MG|MH|ML|MM|MN|MO|MP|MQ|MR|MS|MT|MU|MV|MW|MX|MY|MZ|NA|NC|NE|NF|NG|NI|NL|NO|NP|NR|NU|NZ|OM|PA|PE|PF|PG|PH|PK|PL|PM|PN|PR|PS|PT|PW|PY|QA|RE|RO|RS|RU|RW|SA|SB|SC|SD|SE|SG|SH|SI|SJ|SK|SL|SM|SN|SO|SR|ST|SV|SY|SZ|TC|TD|TF|TG|TH|TJ|TK|TL|TM|TN|TO|TR|TT|TV|TW|TZ|UA|UG|UK|UM|US|UY|UZ|VA|VC|VE|VG|VI|VN|VU|WF|WS|YE|YT|ZA|ZM|ZW|UNKNOWN) #IMPLIED >
<!-- Habíamos definido vip como PCDATA pero en realidad puede ser un elemento vacío -->
<!ELEMENT vip EMPTY>
<!-- Cuando se dé el caso de que tengamos una persona que no pertenece al parlamento no tendrá constituency, por tanto su country y region serán NA. Cuando se dé el caso de que una persona sí sea del parlamento, pero no sepamos o el country o el region entonces en ese caso pondremos UNKNOWN -->
<!ELEMENT constituency EMPTY>
<!-- CONSTITUENCY COUNTRY as it was in the very beginning, country meant the country of the person even if he/she didn't belong to the  House, as it is now it is the country which the MP represents, therefore, this element should be required for all MPs, but not for other people. But country is need for ni. And ngo? And what about the special case of Commission, Council... because it is important, how shall we express country for commissioners? In affiliation, because although not elected directly by citizens for a particular role in the EU institutions they represent their country or cover a quote of power for their country -->
<!ATTLIST constituency country (AD|AE|AF|AG|AI|AL|AM|AN|AO|AQ|AR|AS|AT|AU|AW|AX|AZ|BA|BB|BD|BE|BF|BG|BH|BI|BJ|BL|BM|BN|BO|BR|BS|BT|BV|BW|BY|BZ|CA|CC|CD|CF|CG|CH|CI|CK|CL|CM|CN|CO|CP|CR|CU|CV|CX|CY|CZ|DE|DJ|DK|DM|DO|DZ|EC|EE|EG|EH|EL|ER|ES|ET|FI|FJ|FK|FM|FO|FR|MK|GA|GD|GE|GF|GG|GH|GI|GL|GM|GN|GP|GQ|GS|GT|GU|GW|GY|HK|HM|HN|HR|HT|HU|ID|IE|IL|IM|IN|IO|IQ|IR|IS|IT|JE|JM|JO|JP|KE|KG|KH|KI|KM|KN|KP|KR|KW|KY|KZ|LA|LB|LC|LI|LK|LR|LS|LT|LU|LV|LY|MA|MC|MD|ME|MF|MG|MH|ML|MM|MN|MO|MP|MQ|MR|MS|MT|MU|MV|MW|MX|MY|MZ|NA|NC|NE|NF|NG|NI|NL|NO|NP|NR|NU|NZ|OM|PA|PE|PF|PG|PH|PK|PL|PM|PN|PR|PS|PT|PW|PY|QA|RE|RO|RS|RU|RW|SA|SB|SC|SD|SE|SG|SH|SI|SJ|SK|SL|SM|SN|SO|SR|ST|SV|SY|SZ|TC|TD|TF|TG|TH|TJ|TK|TL|TM|TN|TO|TR|TT|TV|TW|TZ|UA|UG|UK|UM|US|UY|UZ|VA|VC|VE|VG|VI|VN|VU|WF|WS|YE|YT|ZA|ZM|ZW|UNKNOWN|NOT_APPLICABLE) #REQUIRED>
<!-- CONSTITUENCY REGION means any administrative demarcation below country. country #REQUIRED for all corpora, region #IMPLIED for EP and #REQUIRED for CD and HC -->
<!ATTLIST constituency region CDATA #REQUIRED>
<!ELEMENT affiliation (national_party,cd) >
<!ELEMENT cd EMPTY>
<!ATTLIST cd group (GC-CIU|GCC-NC|GER-ERC|GIU-ICV|GMX|GP|GS|GV-EAJ-PNV|UNKNOWN|NA) #REQUIRED >
<!ELEMENT national_party (#PCDATA) >
<!-- Siempre aparecerá la etiqueta post pero cuando no aparezca el cargo en el las actas pondremos NA -->
<!-- En versiones futuras convendrá estudiar los distintos tipos de cargos de cada parlamento y desarrollar unos atributos que permitan describirlos, homogeneizarlos y cruzarlos -->
<!ELEMENT post (#PCDATA)>
<!ELEMENT speech (#PCDATA|omit|italics|page_number)*>
<!-- <!ELEMENT speech (p|omit)+> -->
<!-- SPEECH LANGUAGE in EP should include all official languages plus UNKNOWN, in CD all official languages in the state (Spanish, Catalan, Basque, Galician, Valencian...) and in the HC all official languages (English, Welsh, Gaelic? -->
<!ATTLIST speech language (CS|DA|DE|EL|EN|ES|ET|FI|FR|HU|IT|LT|LV|MT|NL|PL|PT|SK|SL|SV|UNKNOWN) #REQUIRED>
<!-- Add other new languages, since ECPC will gather debates belonging to sessions held after Romanian, Bulgarian, Gaelic and other new languages were incorporated -->
<!ATTLIST speech id ID #REQUIRED>
<!-- This attribute must be required in the definitive version, again remember, should ID attributes be unique only for the text or for the whole corpus instead? -->
<!--  <!ELEMENT p (s|omit)+> -->
<!-- P ID again remember, should ID attributes be unique only for the text or for the whole corpus instead? -->
<!-- <!ATTLIST p id ID #REQUIRED> -->
<!-- <!ELEMENT s (#PCDATA|omit|italics)*> -->
<!-- <!ELEMENT s (#PCDATA|omit|italics)*> -->
<!-- S ID again remember, should ID attributes be unique only for the text or for the whole corpus instead? -->
<!-- <!ATTLIST s id ID #REQUIRED>  -->
<!ELEMENT italics (#PCDATA)>
<!ELEMENT writer (name,birth_date,birth_place,status,gender,institution,constituency,affiliation?,post?) >
<!ELEMENT writing (#PCDATA|omit|italics|page_number)*>
<!-- <!ELEMENT writing (p|omit)+> -->
<!-- WRITING REF again remember, should ID attributes be unique only for the text or for the whole corpus instead? -->
<!-- This attribute must be required and in the definitive version -->
<!ATTLIST writing id ID #REQUIRED>
<!-- Add other new languages, since ECPC will gather debates belonging to sessions held after Romanian, Bulgarian, Gaelic and other new languages were incorporated -->
<!ATTLIST writing language (CS|DA|DE|EL|EN|ES|ET|FI|FR|HU|IT|LT|LV|MT|NL|PL|PT|SK|SL|SV|UNKNOWN) #REQUIRED>
<!-- Heading en un futuro se convertiría en secciones (temáticas) por lo tanto ya no sería PCDATA sino que incluiría elementos como intervention y omit y tendría atributos o elementos para los temas. Se podría utilizar el EUROVOC o un enfoque basado en tesauros o árboles, convendría examinar la metodología Webmatrix (¿enfocada a la palabra?) -->
<!ELEMENT heading (#PCDATA|page_number)*>
<!ATTLIST heading number CDATA #IMPLIED>
<!-- Omits should not contain any sentece <s>, but a sentece can contain an omit, right? Keep it in mind when revising -->
<!ELEMENT omit (#PCDATA|italics|page_number)*>
<!-- OMIT DESC these attributes have never been used, but they might be a source of inspiration of a more descriptive family of elements -->
<!ATTLIST omit desc (opening|action|reaction|procedure|note|closing) #IMPLIED>
<!ELEMENT back (update,disclaimer)*>
<!ELEMENT update (#PCDATA)>
<!ELEMENT disclaimer (#PCDATA)>

=== calzada/ECPC_GITHUB/CORPUS/CD_validado/pl_005.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ecpc_CD SYSTEM "cd.dtd">
<ecpc_CD>
<header>
<legislature begin="20040402" end="20080401">VIII</legislature>
<title> DIARIO DE SESIONES DEL CONGRESO DE LOS DIPUTADOS PLENO Y DIPUTACIÓN PERMANENTE Año 2004 VIII Legislatura 	Núm. 5 celebrada el miércoles, 28 de abril de 2004 </title>
<label>Sesión plenaria núm. 5 </label>
<date>celebrada el miércoles, 28 de abril de 2004 </date>
<place>CORTES GENERALES</place>
<edition> DIARIO DE SESIONES DEL CONGRESO DE LOS DIPUTADOS PLENO Y DIPUTACIÓN PERMANENTE Año 2004 VIII Legislatura 	Núm. 5 </edition>
<index>
<indexitem>
ORDEN DEL DÍA:
Toma en consideración de Proposición de reforma del Reglamento del Congreso de los Diputados: — 	Del Grupo Parlamentario Socialista del Congreso, de reforma del Reglamento del Congreso de los Diputados, por la que se modifica el artículo 46.1. «BOCG. Congreso de los Diputados», Serie B, número 69-1, de 23 de abril de 2004. <omit>(Número de expediente 410/000004.)</omit> . . <page_number>Páginas173 </page_number>Tramitación directa y en lectura única de Proposición de reforma del Reglamento del Congreso de los Diputados : — 	Proposición de reforma del Reglamento del Congreso de los Diputados, por la que se modifica el artículo 46.1. «BOCG. Congreso de los Diputados», Serie B, número 69-1, de 23 de abril de 2004. <omit>(Núm. expte. 410/000004.)</omit> . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . <page_number>Páginas176 </page_number>
</indexitem>
<indexitem>
SUMARIO: 
Se reanuda la sesión a las nueve y cinco minutos de la mañana. Página Toma en consideración de proposición de reforma del Reglamento del Congreso de los Diputados . . . . . . . . . . . . . . . . . <page_number>Páginas173 </page_number>Página Del Grupo Parlamentario Socialista del Congreso, de reforma del Reglamento del Congreso de los Diputados, por la que se modifica el artículo 46.1 . . . . . <page_number>Páginas173 </page_number>
La señora Cunillera i Mestres presenta, en nombre del Grupo Parlamentario Socialista del Congreso, la proposición no de ley que tiene como único objetivo reformar el artículo 46.1 del Reglamento, que se ciñe a las comisiones permanentes legislativas en las que se ordena el trabajo de la Cámara y que sufrió su última revisión el 11 de mayo de 2000. El Real Decreto-ley 562/2004, de 19 de abril, aprueba la estructura orgánica básica de los departamentos ministeriales y la modificación que hoy se somete a la Cámara obedece a una adecuación de las comisiones permanentes legislativas a la estructura de que se ha dotado el Gobierno. Se trata, dice, de sintonizar la estructura del Gobierno y las comisiones legislativas, tal y como ha venido siendo práctica habitual a lo largo de las legislaturas. Resalta la incorporación de una nueva comisión legislativa permanente y muestra su agradecimiento a los grupos minoritarios de las Cámara que van a apoyar la toma en consideración de esta proposición y su posterior aprobación. 
En turno de fijación de posiciones intervienen los señores Jané i Guasch, del Grupo Parlamentario Catalán (Convergència i Unió), y Atencia Robledo, del Grupo Parlamentario Popular en el Congreso. 
Tras dos intentos fallidos de votación electrónica, la Presidencia solicita el voto a mano alzada, quedando aprobada la toma en consideración de la proposición de reforma del artículo 46.1 del Reglamento del Congreso de los Diputados. 
A continuación, la Presidencia, oída la Junta de Portavoces y de conformidad con lo dispuesto en el artículo 150 del Reglamento, somete a la aprobación de la Cámara la tramitación directa y en lectura única por el propio Pleno de la proposición de reforma del artículo 46.1 del Reglamento del Con
greso de los Diputados, lo que se aprueba por asentimiento. 
Se suspende la sesión hasta las diez y treinta minutos, hora en la que concluirá el plazo de presentación de enmiendas. 
Se reanuda la sesión a las diez y cuarenta minutos de la mañana. Página Tramitación directa y en lectura única de proposición de reforma del Reglamento del Congreso de los Diputados . . . . . . <page_number>Páginas176 </page_number>Página Proposición de reforma del Reglamento del Congreso de los Diputados por la que se modifica el artículo 46.1 . . . . . <page_number>Páginas176 </page_number>
El señor Atencia Robledo defiende una enmienda presentada por el Grupo Parlamentario Popular en el Congreso en la que se propone el desdoblamiento de algunas comisiones: una comisión específica de Justicia y otra de Interior, así como una de Fomento y otra de Vivienda. 
Contesta la señora Cunillera i Mestres, en nombre del Grupo Parlamentario Socialista del Congreso, aceptando la propuesta de desdoblamiento de la Comisión de Justicia en Justicia e Interior. 
En turno de fijación de posiciones intervienen los señores Jané i Guasch, del Grupo Parlamentario Catalán (Convergència i Unió), y Atencia Robledo, del Grupo Parlamentario Popular en el Congreso. 
Sometida a votación la enmienda transaccional planteada por el Grupo Parlamentario Socialista del Congreso, se aprueba por 319 votos a favor y dos abstenciones. 
Sometida a votación de conjunto, de acuerdo con el artículo 152 del Reglamento, se aprueba la reforma del Reglamento del Congreso de los Diputados por unanimidad. 
Se levanta la sesión a las diez y cincuenta y cinco minutos de la mañana. 
Se reanuda la sesión a las nueve y cinco minutos de la mañana. 
</indexitem>
</index>
</header>

<body>

<chair who="Marín González, Manuel">

<heading>
TOMA EN CONSIDERACIÓN DE PROPOSI-CIÓN DE REFORMA DEL REGLAMENTO DEL CONGRESO DE LOS DIPUTADOS. — 	DEL GRUPO PARLAMENTARIO SOCIALIS-TA DEL CONGRESO, DE REFORMA DEL REGLAMENTO DEL CONGRESO DE LOS DIPUTADOS, POR LA QUE SE MODIFICA EL ARTÍCULO 46.1. <omit>(Número de expediente 410/000004.)</omit> 
</heading>

<intervention>
<speaker>
<name>MARÍN GONZÁLEZ</name>
<post>PRESIDENTE</post>
</speaker>
<speech language="ES">
 Señorías, se reanuda la sesión. 
Se va a proceder al debate sobre la reforma del Reglamento del Congreso de los Diputados, que tal y como figura en la disposición segunda del propio Reglamento se debe tramitar por el procedimiento establecido para las proposiciones de ley de iniciativa del Congreso. Como se señala también en esta disposición, su aprobación requerirá una votación final de totalidad por mayoría absoluta. El debate se desarrollará de conformidad con lo dispuesto para los debates de totalidad. Asimismo, se ha comunicado a la Mesa que se ha solicitado la tramitación de la iniciativa presentada por el procedimiento de lectura única. Se ha producido un acuerdo de los portavoces, que me ha sido comunicado esta mañana, de que el plazo de enmiendas será de una hora. Así pues, doy por advertidos a los distintos grupos parlamentarios. 
Por parte de los proponentes, tiene la palabra la señora Cunillera. 
En principio el turno a favor es de 15 minutos, pero si puede ahorrar tiempo, mejor. Gracias. 
</speech>
</intervention>

<intervention>
<speaker>
<name>CUNILLERA I MESTRES</name>
<post>NA</post>
</speaker>
<speech language="ES">
 Sí, señor presidente, lo intentaremos. 
Intervengo brevemente para defender la proposición de ley que nuestro grupo presenta hoy a debate y que tiene como único objetivo reformar el artículo 46.1 del Reglamento, que se ciñe a las comisiones permanentes legislativas en las que se ordena el trabajo de la Cámara y que sufrió su última revisión el 11 de mayo de 2000. El Real Decreto-ley 562/2004, de 19 de abril, aprueba la estructura orgánica básica de los departamentos ministeriales. Al igual que en aquel momento, la modificación que hoy sometemos a la Cámara obedece a una adecuación de las comisiones permanentes legislativas a la estructura de que se ha dotado el Gobierno, de tal manera que, en primer lugar, desaparece la Comisión de Ciencia y Tecnología, igual que ha desaparecido el ministerio del mismo nombre, cuyas competencias se han distribuido entre varios ministerios, a saber: los de Industria, Turismo y Comercio y Educación y Ciencia. Estamos, pues, en la desaparición lógica de una comisión existente en la anterior legislatura, comisión que ninguno de nosotros vamos a echar de menos dado la trayectoria que tuvo. Sin embargo, sí me gustaría recordar aquí el vigor y la generosidad con que la defendió en su momento, mayo de 2000, el diputado Núñez, del Grupo Popular, con más voluntad que acierto. A pesar de que la Comisión correspondiente al Ministerio de Ciencia no tuvo el resultado esperado, quisiera recordar al que fue su presidente durante toda la legislatura, el señor Xavier Trías.
